### PR TITLE
updated oauth request with this instead of self

### PR DESCRIPTION
**Pull request by joshterrill**

### CODE REVIEW

**Comment by softprops** [comment]
Thanks for the patch. This repo is honestly no longer very maintained I'd be happy to transfer ownership if you are interested in taking it over

**Comment by joshterrill** [comment]
That would be cool. I’m working with it right now, and there are a few issues I’ve come across.

**Comment by softprops** [comment]
It looks like github won't let me do the ownership transfer since you have a fork with the same name. Can you rename or delete your fork and ling me back. Then I'll try the repo transfer again

**Comment by joshterrill** [comment]
Done

**Comment by softprops** [comment]
hrm I'm still get this error when I try to make the transfer `joshterrill already has a repository in the softprops/meetup-js network` I think you may have to delete the fork to perform the operation.

**Comment by joshterrill** [comment]
Done!

**Comment by softprops** [comment]
I see `Repository transfer to joshterrill requested` so I'm assuming github will send you some notification.  It's all yours, enjoy!

**Pull request merged**
